project:
  type: website
  render:
    - "*.qmd"
website:
  title: "AIML4OS Funathon - Project 2"
  page-navigation: true
  description: "Automatic classification"
  site-url: "https://AIML4OS.github.io/funathon-project2/"
  repo-url: "https://github.com/AIML4OS/funathon-project2"
  repo-actions: [edit, issue]

  open-graph: true

  page-footer:
    right:
    - text: "License"
      href: LICENCE

  navbar:
    align: center
    title: false
    collapse-below: lg
 
    right:
      - icon: github
        href: "https://github.com/AIML4OS/funathon-project2"
        aria-label: GitHub

    left:
      - text: "Introduction"
        href: index.qmd
      - text: "Supervised learning"
        href: 1-ttc.qmd
      - text: "RAG - Introduction"
        href: 2-rag-intro.qmd
      - text: "RAG - Create the vector DB"
        href: 2-rag-vdb.qmd
      - text: "RAG - Generate predictions"
        href: 2-rag-generation.qmd


format:
  html:
    theme:
      light: [cosmo, custom.scss]
    grid:
      body-width: 1100px
    toc: true
    reference-location: margin
    code-copy: true
    code-overflow: wrap
    lightbox: true

execute: 
  eval: true
  cache: true
  warning: false
